"""Create phase 2 phase 3 tables

Revision ID: 6975bfc83302
Revises: 
Create Date: 2026-07-20 12:19:18.702213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6975bfc83302'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bolus_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('activity', sa.Float(), nullable=True),
    sa.Column('temp_without_drinkcycles', sa.Float(), nullable=True),
    sa.Column('normal_temperature', sa.Float(), nullable=True),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.Column('rumination_min_24h', sa.Float(), nullable=True),
    sa.Column('water_intake_l', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bolus_records_cow_id'), 'bolus_records', ['cow_id'], unique=False)
    op.create_index(op.f('ix_bolus_records_id'), 'bolus_records', ['id'], unique=False)
    op.create_index(op.f('ix_bolus_records_record_type'), 'bolus_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_bolus_records_timestamp'), 'bolus_records', ['timestamp'], unique=False)
    op.create_table('contraction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('peak_time', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('peak_amplitude', sa.Float(), nullable=True),
    sa.Column('prominence', sa.Float(), nullable=True),
    sa.Column('width_seconds', sa.Float(), nullable=True),
    sa.Column('movement_flag_near_peak', sa.Integer(), nullable=True),
    sa.Column('movement_score_near_peak', sa.Float(), nullable=True),
    sa.Column('event_label', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contraction_events_cow_id'), 'contraction_events', ['cow_id'], unique=False)
    op.create_index(op.f('ix_contraction_events_id'), 'contraction_events', ['id'], unique=False)
    op.create_index(op.f('ix_contraction_events_peak_time'), 'contraction_events', ['peak_time'], unique=False)
    op.create_table('contraction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('file_order', sa.Integer(), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('global_sample_index', sa.Integer(), nullable=False),
    sa.Column('acc_x', sa.Float(), nullable=True),
    sa.Column('acc_y', sa.Float(), nullable=True),
    sa.Column('acc_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('movement_flag', sa.Float(), nullable=True),
    sa.Column('unknown_1', sa.Float(), nullable=True),
    sa.Column('unknown_2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contraction_records_cow_id'), 'contraction_records', ['cow_id'], unique=False)
    op.create_index(op.f('ix_contraction_records_id'), 'contraction_records', ['id'], unique=False)
    op.create_index(op.f('ix_contraction_records_timestamp'), 'contraction_records', ['timestamp'], unique=False)
    op.create_table('cows',
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('calving_datetime', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cow_id')
    )
    op.create_table('file_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('raw_file_path', sa.Text(), nullable=False),
    sa.Column('upload_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cow_id', 'data_type', 'file_hash', name='uq_cow_data_file_hash')
    )
    op.create_index(op.f('ix_file_records_cow_id'), 'file_records', ['cow_id'], unique=False)
    op.create_index(op.f('ix_file_records_data_type'), 'file_records', ['data_type'], unique=False)
    op.create_index(op.f('ix_file_records_file_hash'), 'file_records', ['file_hash'], unique=False)
    op.create_index(op.f('ix_file_records_id'), 'file_records', ['id'], unique=False)
    op.create_index(op.f('ix_file_records_source_file'), 'file_records', ['source_file'], unique=False)
    op.create_table('processed_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('dataset_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_datasets_cow_id'), 'processed_datasets', ['cow_id'], unique=False)
    op.create_index(op.f('ix_processed_datasets_dataset_type'), 'processed_datasets', ['dataset_type'], unique=False)
    op.create_index(op.f('ix_processed_datasets_id'), 'processed_datasets', ['id'], unique=False)
    op.create_table('qc_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_logs_cow_id'), 'qc_logs', ['cow_id'], unique=False)
    op.create_index(op.f('ix_qc_logs_id'), 'qc_logs', ['id'], unique=False)
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('raw_folder_path', sa.Text(), nullable=False),
    sa.Column('processed_file_path', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_batches_cow_id'), 'upload_batches', ['cow_id'], unique=False)
    op.create_index(op.f('ix_upload_batches_id'), 'upload_batches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_batches_id'), table_name='upload_batches')
    op.drop_index(op.f('ix_upload_batches_cow_id'), table_name='upload_batches')
    op.drop_table('upload_batches')
    op.drop_index(op.f('ix_qc_logs_id'), table_name='qc_logs')
    op.drop_index(op.f('ix_qc_logs_cow_id'), table_name='qc_logs')
    op.drop_table('qc_logs')
    op.drop_index(op.f('ix_processed_datasets_id'), table_name='processed_datasets')
    op.drop_index(op.f('ix_processed_datasets_dataset_type'), table_name='processed_datasets')
    op.drop_index(op.f('ix_processed_datasets_cow_id'), table_name='processed_datasets')
    op.drop_table('processed_datasets')
    op.drop_index(op.f('ix_file_records_source_file'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_id'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_file_hash'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_data_type'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_cow_id'), table_name='file_records')
    op.drop_table('file_records')
    op.drop_table('cows')
    op.drop_index(op.f('ix_contraction_records_timestamp'), table_name='contraction_records')
    op.drop_index(op.f('ix_contraction_records_id'), table_name='contraction_records')
    op.drop_index(op.f('ix_contraction_records_cow_id'), table_name='contraction_records')
    op.drop_table('contraction_records')
    op.drop_index(op.f('ix_contraction_events_peak_time'), table_name='contraction_events')
    op.drop_index(op.f('ix_contraction_events_id'), table_name='contraction_events')
    op.drop_index(op.f('ix_contraction_events_cow_id'), table_name='contraction_events')
    op.drop_table('contraction_events')
    op.drop_index(op.f('ix_bolus_records_timestamp'), table_name='bolus_records')
    op.drop_index(op.f('ix_bolus_records_record_type'), table_name='bolus_records')
    op.drop_index(op.f('ix_bolus_records_id'), table_name='bolus_records')
    op.drop_index(op.f('ix_bolus_records_cow_id'), table_name='bolus_records')
    op.drop_table('bolus_records')
    # ### end Alembic commands ###
